version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: dinky98/ui:3.0
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
      - back_net
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: dinky98/post:3.0
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post


  comment:
    image: dinky98/comment:3.0
    networks:
      - front_net
      - back_net


  prometheus:
    image: dinky98/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

volumes:
  prometheus_data:

volumes:
  post_db:

networks:
    front_net:
        driver: bridge
    back_net:
        driver: bridge


