---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: reddit
    component: mongo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: reddit
    component: mongo
